# Generated by Django 2.2.5 on 2019-09-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_quotepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotepage',
            name='radiobutton_1',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='quotepage',
            name='radiobutton_2',
            field=models.BooleanField(default='False'),
        ),
    ]
