# Generated by Django 2.2.5 on 2019-09-07 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_auto_20190907_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotepage',
            old_name='radiobutton_2',
            new_name='get_started_this_week',
        ),
        migrations.RenameField(
            model_name='quotepage',
            old_name='name',
            new_name='just_research',
        ),
        migrations.RemoveField(
            model_name='quotepage',
            name='radiobutton_1',
        ),
    ]
