# Generated by Django 2.2.5 on 2019-09-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_auto_20190907_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotepage',
            old_name='get_started_this_week',
            new_name='research',
        ),
        migrations.RemoveField(
            model_name='quotepage',
            name='just_research',
        ),
        migrations.AddField(
            model_name='quotepage',
            name='this_week',
            field=models.BooleanField(default=True),
        ),
    ]
