# Generated by Django 2.2.5 on 2019-09-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_auto_20190907_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotepage',
            name='research',
        ),
        migrations.RemoveField(
            model_name='quotepage',
            name='this_week',
        ),
    ]
