# Generated by Django 2.2.5 on 2019-09-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0010_auto_20190907_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inquiry_email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('SOCIAL MEDIA MARKETING', 'Social Media Marketing'), ('WEBSITE DEVELOPMENT', 'Website Development'), ('SEO AND WEBSITE DEVELOPMENT', 'SEO & Website Development'), ('SEO, SMO AND WEBSITE DEVELOPMENT', 'SEO, SMO & Website Development'), ('EXECUTIVE', 'I want to talk to your executive.')], default='SOCIAL MEDIA MARKETING', max_length=100)),
                ('requirements', models.CharField(max_length=500)),
            ],
        ),
    ]
